typedef enum
{
  STATE_NORMAL = 0,
  STATE_READY,
  STATE_DOWNLOADING,
  STATE_DOWNLOADED,
  STATE_INSTALLING,
  STATE_INSTALLED,
  STATE_CANCEL,
  STATE_CLOSE,
  STATE_ERROR,
  N_STATE
} InstallState;
