#!/bin/bash
CMD=""

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 [options]"
	exit 1
fi

args=("$@")

for (( i=0; i<$#; i++ ))
do
	CMD="$CMD${args[$i]} "
done

echo "apt install $CMD-y"
apt install --reinstall $CMD -y
