#!/bin/bash
CMD=""

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 [options]"
	exit 1
fi

args=("$@")

for (( i=1; i<$#; i++ ))
do
	CMD="$CMD${args[$i]} "
done

if [ "$1" -eq 0 ]; then
    apt purge $CMD -y > /dev/null 2>&1
else
    apt install --reinstall $CMD -y > /dev/null 2>&1
fi
